#!/usr/bin/env bash
# du-convert.sh — convert a native DocuBrowse install to the Docker stack
# WITHOUT re-scanning. Reuses the existing index (du-docs.db) in place by
# mounting each indexed document root at its own absolute path, so the
# absolute paths stored in the DB resolve unchanged inside the container.
#
# LINUX ONLY. Docker does not run natively on macOS or Windows — it runs inside
# a Linux VM there, and the native index's absolute paths (/Users/... or
# C:\...) cannot be mounted 1:1 into that VM. On macOS/Windows, install the
# Docker stack fresh and do a full scan + configure your document directories
# in the web UI; the native index cannot be reused there.
#
# Runs under bash and zsh (zsh executes this bash script directly).
#
#   ./du-convert.sh              # discover roots, mount them, bring the stack up
#   ./du-convert.sh --dry-run    # show what it would do, touch nothing
#
# Document roots are discovered from the app's own config (no hardcoding):
#   $DATA_DIR/docubrowse.config   ->  doc_dir = <primary root>
#   $DATA_DIR/scan_dirs.txt       ->  additional roots, one per line
# DATA_DIR defaults to ~/.docubrowser (override with DOCUBROWSE_DATA_DIR).
set -euo pipefail

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && { DRY_RUN=1; shift; }

DATA_DIR="${DOCUBROWSE_DATA_DIR:-$HOME/.docubrowser}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
COMPOSE="$SCRIPT_DIR/docker-compose.yml"
CONFIG="$DATA_DIR/docubrowse.config"
SCAN_DIRS="$DATA_DIR/scan_dirs.txt"
OVERRIDE="$DATA_DIR/docker-compose.override.yml"   # generated in DATA_DIR, never the repo
ENV_FILE="$DATA_DIR/docker.env"                     # generated in DATA_DIR, never the repo

# ── Platform guard ────────────────────────────────────────────────────────────
if [[ "$(uname -s)" != "Linux" ]]; then
  echo "ERROR: du-convert.sh is Linux-only." >&2
  echo "Docker runs in a Linux VM on macOS/Windows, so the native index's paths" >&2
  echo "cannot be mounted 1:1. Install the Docker stack fresh there and do a full" >&2
  echo "scan + configure document dirs in the web UI." >&2
  exit 1
fi

[[ -f "$COMPOSE" ]] || { echo "ERROR: docker-compose.yml not found next to this script ($COMPOSE)" >&2; exit 1; }
[[ -f "$DATA_DIR/du-docs.db" ]] || { echo "ERROR: no du-docs.db in $DATA_DIR — nothing to reuse." >&2; exit 1; }

# ── Discover document roots ───────────────────────────────────────────────────
roots=()
if [[ -f "$CONFIG" ]]; then
  d="$(sed -n 's/^[[:space:]]*doc_dir[[:space:]]*=[[:space:]]*//p' "$CONFIG" | head -1)"
  [[ -n "$d" ]] && roots+=("$d")
fi
if [[ -f "$SCAN_DIRS" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%%#*}"                     # strip trailing comment
    line="${line#"${line%%[![:space:]]*}"}"  # ltrim
    line="${line%"${line##*[![:space:]]}"}"  # rtrim
    [[ -n "$line" ]] && roots+=("$line")
  done < "$SCAN_DIRS"
fi
[[ ${#roots[@]} -gt 0 ]] || { echo "ERROR: no document roots in $CONFIG or $SCAN_DIRS" >&2; exit 1; }

# de-duplicate, preserving order
mapfile -t roots < <(printf '%s\n' "${roots[@]}" | awk '!seen[$0]++')

echo "Discovered ${#roots[@]} document root(s):"
for r in "${roots[@]}"; do
  if [[ -d "$r" ]]; then echo "  ✓ $r"; else echo "  ✗ $r  (NOT found on host — its docs will still read as not-on-disk)"; fi
done

primary="${roots[0]}"
extras=("${roots[@]:1}")

# ── Generate the override for extra roots (primary goes via DOCUBROWSE_DOC_DIR) ─
gen_override() {
  echo "# GENERATED by du-convert.sh — do not edit. Re-run to refresh."
  echo "services:"
  echo "  docubrowse:"
  echo "    volumes:"
  for r in "${extras[@]}"; do
    printf '      - "%s:%s:ro"\n' "$r" "$r"
  done
}

compose_files=(-f "$COMPOSE")
if ((${#extras[@]})); then
  compose_files+=(-f "$OVERRIDE")
fi

if ((DRY_RUN)); then
  echo
  echo "[dry-run] env-file ($ENV_FILE) would contain:"
  echo "  UID=$(id -u)"
  echo "  GID=$(id -g)"
  echo "  DOCUBROWSE_DATA_DIR=$DATA_DIR"
  echo "  DOCUBROWSE_DOC_DIR=$primary"
  if ((${#extras[@]})); then
    echo "[dry-run] override ($OVERRIDE) would contain:"
    gen_override | sed 's/^/  /'
  else
    echo "[dry-run] single root — no override needed."
  fi
  echo "[dry-run] would run: docker compose --env-file $ENV_FILE ${compose_files[*]} up -d"
  exit 0
fi

# ── Write generated files + bring the stack up ────────────────────────────────
printf 'UID=%s\nGID=%s\nDOCUBROWSE_DATA_DIR=%s\nDOCUBROWSE_DOC_DIR=%s\n' \
  "$(id -u)" "$(id -g)" "$DATA_DIR" "$primary" > "$ENV_FILE"
((${#extras[@]})) && gen_override > "$OVERRIDE"

docker compose --env-file "$ENV_FILE" "${compose_files[@]}" up -d "$@"

echo
echo "DocuBrowse (Docker) is up — index reused in place, no rescan."
echo "  UI: http://localhost:8643"
echo "  Roots mounted read-only at their native paths."
